#!/bin/zsh

if [ -z "$1" ]
  then
    echo "No argument supplied"
  exit
fi


DAY=$1
mkdir -p $DAY/input
cat .template.php | sed "s/XXX/$DAY/g" > $DAY/$DAY.php
composer update
rm composer.development.json